# --- Main Colors ---
background            #1a120d
foreground            #f0dfd7
cursor                #f0dfd7
cursor_text_color     #1a120d

selection_background  #5c4131
selection_foreground  #ffdbc8

url_color             #cbc992

# --- ANSI Colors ---
color0                #1a120d
color1                #ffb4ab
color2                #cbc992
color3                #e5bfa9
color4                #ffb68a
color5                #cbc992
color6                #e5bfa9
color7                #f0dfd7

color8                #52443c
color9                #93000a
color10               #49491e
color11               #5c4131
color12               #6f3811
color13               #5c4131
color14               #49491e
color15               #d7c2b8

# --- Starship Prompt Bubbles ---
color255              #6f3811
color254              #ffb68a
color253              #5c4131
color252              #e5bfa9
color251              #49491e
color250              #cbc992
color249              #93000a
color248              #ffb4ab

color232              #ffdbc8
color233              #522300
color234              #ffdbc8
color235              #432b1c
color236              #e8e5ac
color237              #333209
color238              #ffdad6
color239              #690005
color240              #ffdbc8

# Matched with unthemed light/dark
color243              #ffb68a
color244              #ffb4ab
color245              #52443c

# --- UI Elements ---
active_tab_foreground   #522300
active_tab_background   #ffb68a
inactive_tab_foreground #ffdbc8
inactive_tab_background #6f3811

active_border_color     #ffb68a
inactive_border_color   #9f8d84

# --- Marks ---
mark1_foreground        #321300
mark1_background        #ffdbc8
mark2_foreground        #2b1609
mark2_background        #ffdbc8
mark3_foreground        #1d1d00
mark3_background        #e8e5ac
